export enum BookGenre {
  ADVENTURE = 'Adventure',
  BIOGRAPHY = 'Biography',
  BUSINESS = 'Business',
  CHILDRENS_BOOK = `Children's Book`,
  COMEDY = 'Comedy',
  COOKBOOK = 'Cookbook',
  DRAMA = 'Drama',
  FANTASY = 'Fantasy',
  GAME = 'Game',
  FICTION = 'Fiction',
  HISTORY = 'History',
  HORROR = 'Horror',
  MYSTERY = 'Mystery',
  NONFICTION = 'Nonfiction',
  PHILOSOPHY = 'Philosophy',
  POETRY = 'Poetry',
  PSYCHOLOGY = 'Psychology',
  RELIGION = 'Religion',
  ROMANCE = 'Romance',
  SCI_FI = 'Sci-fi',
  SCIENCE = 'Science',
  THRILLER = 'Thriller',
}
